# Generated by Django 4.2.2 on 2023-09-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testthomas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testthomas',
            name='iliopsoasdir',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testthomas',
            name='iliopsoasesq',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testthomas',
            name='retofemoraldir',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testthomas',
            name='retofemuralesq',
            field=models.BooleanField(default=False),
        ),
    ]
