# Generated by Django 4.2.2 on 2023-09-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testquedapelvica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquedapelvica',
            name='direito',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testquedapelvica',
            name='esquerdo',
            field=models.BooleanField(default=False),
        ),
    ]
