# Generated by Django 3.2.12 on 2023-07-01 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teste', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testmuscular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abduquadrildir', models.CharField(max_length=15)),
                ('abduquadrilesq', models.CharField(max_length=15)),
                ('rotquadrildir', models.CharField(max_length=15)),
                ('rotquadrilesq', models.CharField(max_length=15)),
                ('flexplantardir', models.CharField(max_length=15)),
                ('flexplantaresq', models.CharField(max_length=15)),
                ('flexjoelhodir', models.CharField(max_length=15)),
                ('flexjoelhoesq', models.CharField(max_length=15)),
                ('exjoelhodir', models.CharField(max_length=15)),
                ('exjoelhoesq', models.CharField(max_length=15)),
                ('teste', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teste.teste')),
            ],
            options={
                'verbose_name': 'Teste muscular',
                'verbose_name_plural': 'Testes musculares',
            },
        ),
    ]
