# Generated by Django 4.2.2 on 2023-10-23 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teste', '0001_initial'),
        ('desvam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesempenhoDesvam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vam_2km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('vam_3km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('teste', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teste.teste')),
            ],
            options={
                'verbose_name': 'DesempenhoDesvam',
            },
        ),
    ]
