# Generated by Django 3.2.12 on 2023-07-01 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teste', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimulo_1', models.CharField(max_length=15)),
                ('estimulo_2', models.CharField(max_length=15)),
                ('estimulo_3', models.CharField(max_length=15)),
                ('estimulo_4', models.CharField(max_length=15)),
                ('estimulo_5', models.CharField(max_length=15)),
                ('estimulo_6', models.CharField(max_length=15)),
                ('teste', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teste.teste')),
            ],
            options={
                'verbose_name': 'Rast',
            },
        ),
    ]
