# Generated by Django 4.2.2 on 2023-10-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antropometria', '0003_antropometria_altura'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculoantropometria',
            name='gordcorporal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='calculoantropometria',
            name='imc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='calculoantropometria',
            name='massamagra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
