# Generated by Django 4.2.2 on 2023-10-26 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antropometria', '0004_calculoantropometria_gordcorporal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculoantropometria',
            old_name='densicorphomem',
            new_name='densicorporal',
        ),
        migrations.RenameField(
            model_name='calculoantropometria',
            old_name='densicorpmulher',
            new_name='percgordura',
        ),
        migrations.RemoveField(
            model_name='calculoantropometria',
            name='percgordhomem',
        ),
        migrations.RemoveField(
            model_name='calculoantropometria',
            name='percgordmulher',
        ),
    ]
