# Generated by Django 3.2.12 on 2023-07-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Modalidade',
            },
        ),
    ]
