# Generated by Django 4.2.2 on 2023-08-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modalidade_historico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalidade_historico',
            name='vigencia_final',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='modalidade_historico',
            name='vigencia_inicial',
            field=models.DateField(blank=True),
        ),
    ]
