# Generated by Django 4.2.2 on 2023-09-01 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atleta', '0001_initial'),
        ('modalidade', '0001_initial'),
        ('usuario', '0002_usuario_administrador'),
        ('modalidade_historico', '0002_alter_modalidade_historico_vigencia_final_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modalidades_atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=False)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='atleta.atleta')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='modalidade.modalidade')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='usuario.usuario')),
            ],
            options={
                'verbose_name': 'Modalidades do Atleta',
            },
        ),
        migrations.DeleteModel(
            name='Modalidade_historico',
        ),
    ]
