# Generated by Django 3.2.12 on 2023-07-01 20:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modalidade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=11)),
                ('data_nasc', models.DateField(default=datetime.date.today)),
                ('cel_resp', models.CharField(max_length=11)),
                ('grau_instrucao', models.CharField(max_length=100)),
                ('origem_escolar', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=11)),
                ('sexo', models.CharField(max_length=10)),
                ('modalidade_atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modalidade.modalidade')),
            ],
            options={
                'verbose_name': 'Atleta',
            },
        ),
    ]
