from django.urls import path
from . import views
from django.conf import settings

urlpatterns = [
    path('', views.home, name="home_dashboard"),
    path('periodo_painel', views.periodo_painel, name="periodo_painel"),
    path('valida_periodo_painel', views.valida_periodo_painel, name="valida_periodo_painel"),
    path('atleta/<int:atleta_id>', views.painel_atleta, name="painel_atleta"),
    path('retorna_total_consultas', views.retorna_total_consultas, name="retorna_total_consultas"),
    path('retorna_total_consultas_atleta/<int:atleta_id>', views.retorna_total_consultas_atleta, name="retorna_total_consultas_atleta"),
    path('retorna_total_testes', views.retorna_total_testes, name="retorna_total_testes"),
    path('retorna_total_testes_atleta/<int:atleta_id>', views.retorna_total_testes_atleta, name="retorna_total_testes_atleta"),
    path('relatorio_testes', views.relatorio_testes, name="relatorio_testes"),
    path('relatorio_atletas_modalidade', views.relatorio_atletas_modalidade, name="relatorio_atletas_modalidade"),
    path('relatorio_angpopliteo_atleta/<int:atleta_id>', views.relatorio_angpopliteo_atleta, name="relatorio_angpopliteo_atleta"),
    path('relatorio_antropometria_atleta/<int:atleta_id>', views.relatorio_antropometria_atleta, name="relatorio_antropometria_atleta"),
    path('relatorio_calculoantropometria_atleta/<int:atleta_id>', views.relatorio_calculoantropometria_atleta, name="relatorio_calculoantropometria_atleta"),
    path('relatorio_compmembinf_atleta/<int:atleta_id>', views.relatorio_compmembinf_atleta, name="relatorio_compmembinf_atleta"),
    path('relatorio_condclinica_atleta/<int:atleta_id>', views.relatorio_condclinica_atleta, name="relatorio_condclinica_atleta"),
    path('relatorio_corrida_atleta/<int:atleta_id>', views.relatorio_corrida_atleta, name="relatorio_corrida_atleta"),
    path('relatorio_desvam_atleta/<int:atleta_id>', views.relatorio_desvam_atleta, name="relatorio_desvam_atleta"),
    path('relatorio_desempenhodesvam_atleta/<int:atleta_id>', views.relatorio_desempenhodesvam_atleta, name="relatorio_desempenhodesvam_atleta"),
    path('relatorio_dorsiflexao_atleta/<int:atleta_id>', views.relatorio_dorsiflexao_atleta, name="relatorio_dorsiflexao_atleta"),
    path('relatorio_flexibilidade_atleta/<int:atleta_id>', views.relatorio_flexibilidade_atleta, name="relatorio_flexibilidade_atleta"),
    path('relatorio_maiorwellsflexibilidade_atleta/<int:atleta_id>', views.relatorio_maiorwellsflexibilidade_atleta, name="relatorio_maiorwellsflexibilidade_atleta"),
    path('relatorio_fundtecnico_atleta/<int:atleta_id>', views.relatorio_fundtecnico_atleta, name="relatorio_fundtecnico_atleta"),
    path('relatorio_potmusmeminf_atleta/<int:atleta_id>', views.relatorio_potmusmeminf_atleta, name="relatorio_potmusmeminf_atleta"),
    path('relatorio_calculospotmusmeminf_atleta/<int:atleta_id>', views.relatorio_calculospotmusmeminf_atleta, name="relatorio_calculospotmusmeminf_atleta"),
    path('relatorio_rast_atleta/<int:atleta_id>', views.relatorio_rast_atleta, name="relatorio_rast_atleta"),
    path('relatorio_calculorast_atleta/<int:atleta_id>', views.relatorio_calculorast_atleta, name="relatorio_calculorast_atleta"),
    path('relatorio_runmatic_atleta/<int:atleta_id>', views.relatorio_runmatic_atleta, name="relatorio_runmatic_atleta"),
    path('relatorio_assimetriarunmatic_atleta/<int:atleta_id>', views.relatorio_assimetriarunmatic_atleta, name="relatorio_assimetriarunmatic_atleta"),
    path('relatorio_testcadextensora_atleta/<int:atleta_id>', views.relatorio_testcadextensora_atleta, name="relatorio_testcadextensora_atleta"),
    path('relatorio_testey_atleta/<int:atleta_id>', views.relatorio_testey_atleta, name="relatorio_testey_atleta"),
    path('relatorio_testmuscular_atleta/<int:atleta_id>', views.relatorio_testmuscular_atleta, name="relatorio_testmuscular_atleta"),
    path('relatorio_testober_atleta/<int:atleta_id>', views.relatorio_testober_atleta, name="relatorio_testober_atleta"),
    path('relatorio_testprogmaximo_atleta/<int:atleta_id>', views.relatorio_testprogmaximo_atleta, name="relatorio_testprogmaximo_atleta"),
    path('relatorio_testquedapelvica_atleta/<int:atleta_id>', views.relatorio_testquedapelvica_atleta, name="relatorio_testquedapelvica_atleta"),
    path('relatorio_testsalto_atleta/<int:atleta_id>', views.relatorio_testsalto_atleta, name="relatorio_testsalto_atleta"),
    path('relatorio_testthomas_atleta/<int:atleta_id>', views.relatorio_testthomas_atleta, name="relatorio_testthomas_atleta"),
]
