# Generated by Django 3.2.12 on 2023-07-01 20:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atleta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliaAtletismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=datetime.date.today)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('alterado', models.DateTimeField(auto_now=True)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='atleta.atleta')),
            ],
            options={
                'verbose_name': 'Avaliação Atletismo',
                'verbose_name_plural': 'Avaliações Atletismo',
            },
        ),
    ]
