# Generated by Django 4.2.2 on 2023-09-19 16:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 19, 13, 55, 59, 839926)),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='nome_produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.produto'),
        ),
        migrations.AlterField(
            model_name='vendas',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dashboard.vendedor'),
        ),
    ]
