# Generated by Django 4.2.2 on 2023-09-19 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_vendas_data_alter_vendas_nome_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendas',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 19, 14, 9, 10, 844983)),
        ),
    ]
