# Generated by Django 4.2.2 on 2023-10-09 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_vendas_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendas',
            name='nome_produto',
        ),
        migrations.RemoveField(
            model_name='vendas',
            name='vendedor',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.DeleteModel(
            name='Vendas',
        ),
        migrations.DeleteModel(
            name='Vendedor',
        ),
    ]
