# Generated by Django 3.2.12 on 2023-07-01 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teste', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anterior_direito_1', models.CharField(max_length=15)),
                ('anterior_direito_2', models.CharField(max_length=15)),
                ('anterior_direito_3', models.CharField(max_length=15)),
                ('anterior_esquerdo_1', models.CharField(max_length=15)),
                ('anterior_esquerdo_2', models.CharField(max_length=15)),
                ('anterior_esquerdo_3', models.CharField(max_length=15)),
                ('postero_medial_dir_1', models.CharField(max_length=15)),
                ('postero_medial_dir_2', models.CharField(max_length=15)),
                ('postero_medial_dir_3', models.CharField(max_length=15)),
                ('postero_medial_esq_1', models.CharField(max_length=15)),
                ('postero_medial_esq_2', models.CharField(max_length=15)),
                ('postero_medial_esq_3', models.CharField(max_length=15)),
                ('postero_lat_esq_1', models.CharField(max_length=15)),
                ('postero_lat_esq_2', models.CharField(max_length=15)),
                ('postero_lat_esq_3', models.CharField(max_length=15)),
                ('postero_lat_dir_1', models.CharField(max_length=15)),
                ('postero_lat_dir_2', models.CharField(max_length=15)),
                ('postero_lat_dir_3', models.CharField(max_length=15)),
                ('teste', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teste.teste')),
            ],
            options={
                'verbose_name': 'Testey',
            },
        ),
    ]
