# Generated by Django 3.2.12 on 2023-07-01 20:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('atleta', '0001_initial'),
        ('instrutor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('data', models.DateField(default=datetime.date.today)),
                ('criado', models.DateTimeField(auto_now=True)),
                ('alterado', models.DateTimeField(auto_now=True)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='atleta.atleta')),
                ('instrutor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='instrutor.instrutor')),
            ],
            options={
                'verbose_name': 'Teste',
            },
        ),
    ]
