# Generated by Django 3.2.12 on 2023-07-03 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instrutor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11)),
                ('nome', models.CharField(max_length=155)),
                ('email', models.EmailField(max_length=105)),
                ('telefone', models.CharField(max_length=11)),
                ('ativado', models.BooleanField(default=True)),
                ('senha', models.CharField(max_length=64)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('alterado', models.DateTimeField(auto_now=True)),
                ('instrutor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='instrutor.instrutor')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
    ]
