# Generated by Django 3.2.12 on 2023-07-01 20:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instrutor', '0001_initial'),
        ('atleta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('data', models.DateField(default=datetime.date.today)),
                ('receituario', models.TextField(max_length=600)),
                ('relato', models.TextField(max_length=1000)),
                ('sigilo', models.BooleanField(default=False)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('alterado', models.DateTimeField(auto_now=True)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='atleta.atleta')),
                ('instrutor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='instrutor.instrutor')),
            ],
            options={
                'verbose_name': 'Consulta',
            },
        ),
    ]
