# Generated by Django 3.2.12 on 2023-07-01 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teste', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Runmatic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tcontatoesq', models.CharField(max_length=15)),
                ('tcontatodir', models.CharField(max_length=15)),
                ('tvooesq', models.CharField(max_length=15)),
                ('tvoodir', models.CharField(max_length=15)),
                ('freqpassadaesq', models.CharField(max_length=15)),
                ('freqpassadadir', models.CharField(max_length=15)),
                ('osverticalesq', models.CharField(max_length=15)),
                ('osverticaldir', models.CharField(max_length=15)),
                ('stifnessesq', models.CharField(max_length=15)),
                ('stifnessdir', models.CharField(max_length=15)),
                ('fmaximaesq', models.CharField(max_length=15)),
                ('fmaximadir', models.CharField(max_length=15)),
                ('teste', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teste.teste')),
            ],
            options={
                'verbose_name': 'Runmatic',
            },
        ),
    ]
