# Generated by Django 3.2.12 on 2023-07-01 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teste', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corrida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tr', models.CharField(max_length=5)),
                ('c20m', models.CharField(max_length=5)),
                ('muddirecao', models.CharField(max_length=5)),
                ('c10m', models.CharField(max_length=5)),
                ('c30m', models.CharField(max_length=5)),
                ('vift', models.DecimalField(decimal_places=2, max_digits=5)),
                ('teste', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teste.teste')),
            ],
            options={
                'verbose_name': 'Corrida',
            },
        ),
    ]
